---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "monthly"
    labels:
      - "client"
      - "dependencies"
      - "npm"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
      - "server"
