name: Upload package to VSCode Marketplace

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Setup NPM
      run: |
        npm install
        npm install -g vsce ovsx
        npm run compile
    - name: Publish
      if: success()
      run: |
        vsce publish
        ovsx publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        OVSX_PAT: ${{ secrets.OVSX_PAT }}