name: Upload package to VSCode Marketplace

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Setup NPM
      run: |
        npm install
        npm install -g vsce
        npm run compile
    - name: Publish
      if: success()
      run: vsce publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}