name: Update CloudFormation schemas
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch: # Enables on-demand/manual triggering: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
jobs:
  schema-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: aws-cloudformation/aws-cloudformation-template-schema
          path: aws-cloudformation-template-schema
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: |
          cd aws-cloudformation-template-schema
          poetry install
          poetry run cfn-template-schema generate --output-folder specs --type language-server
          rm -Rf ../server/schema/*
          mv specs/* ../server/schema/
          cd ..
          rm -rf aws-cloudformation-template-schema
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: |
            CloudFormation Template Schema upgrade
            https://github.com/aws-cloudformation/cloudformation-template-schema/tree/main
          delete-branch: true
          title: CloudFormation Template Schema upgrade
          body: |
            https://github.com/aws-cloudformation/cloudformation-template-schema/tree/main

            If tests are stuck on https://github.com/peter-evans/create-pull-request/issues/48:
            ["Manually close pull requests and immediately reopen them. This will enable `on: pull_request` workflows to run and be added as checks."](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs)
