on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # Enables on-demand/manual triggering: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
jobs:
  schema-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: aws-cloudformation/aws-cloudformation-template-schema
          path: aws-cloudformation-template-schema
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: |
          cd aws-cloudformation-template-schema
          mvn package
          echo 'settings:
            regions: [us-east-1]
            output: out' > cfg.yml
          java -jar target/aws-cloudformation-template-schema-1.0-SNAPSHOT-jar-with-dependencies.jar --config-file cfg.yml
          mv out/us-east-1/all-spec.json ../schema/all-spec.json
          cd ..
          rm -rf aws-cloudformation-template-schema
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            CloudFormation Template Schema upgrade
            https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues/32
            https://github.com/aws-cloudformation/aws-cloudformation-template-schema/blob/master/docs/tool/instructions.md
            as described in https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/76
          delete-branch: true
          title: CloudFormation Template Schema upgrade
          body: |
            https://github.com/aws-cloudformation/aws-cloudformation-template-schema/issues/32
            https://github.com/aws-cloudformation/aws-cloudformation-template-schema/blob/master/docs/tool/instructions.md
            as described in https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/76

            If tests are stuck on https://github.com/peter-evans/create-pull-request/issues/48:
            ["Manually close pull requests and immediately reopen them. This will enable `on: pull_request` workflows to run and be added as checks."](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs)
